// <auto-generated />
using System;
using AbsurdCourt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbsurdCourt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CourtDbContext))]
    [Migration("20260815125125_ValueGeneratedNeverForIds")]
    partial class ValueGeneratedNeverForIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.CaseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Autos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CaseFiles", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.Defense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSubmitted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRoundId");

                    b.ToTable("Defenses", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("_caseFileSequence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CaseFileSequence");

                    b.Property<string>("_scores")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Scores");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.MatchRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaseFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchRounds", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Rooms.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReconnectToken")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AwaitingRematchSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("_rematchReadyPlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RematchReadyPlayerIds");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.Defense", b =>
                {
                    b.HasOne("AbsurdCourt.Domain.Matches.MatchRound", null)
                        .WithMany("Defenses")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AbsurdCourt.Domain.Matches.Verdict", "Verdict", b1 =>
                        {
                            b1.Property<Guid>("DefenseId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ParecerText")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("VerdictParecerText");

                            b1.Property<int>("Points")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VerdictPoints");

                            b1.HasKey("DefenseId");

                            b1.ToTable("Defenses");

                            b1.WithOwner()
                                .HasForeignKey("DefenseId");
                        });

                    b.Navigation("Verdict");
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.MatchRound", b =>
                {
                    b.HasOne("AbsurdCourt.Domain.Matches.Match", null)
                        .WithMany("Rounds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Rooms.Player", b =>
                {
                    b.HasOne("AbsurdCourt.Domain.Rooms.Room", null)
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Rooms.Room", b =>
                {
                    b.OwnsOne("AbsurdCourt.Domain.Rooms.RoomSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CaseCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SettingsCaseCount");

                            b1.Property<int>("RoundDurationSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SettingsRoundDurationSeconds");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.Match", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Matches.MatchRound", b =>
                {
                    b.Navigation("Defenses");
                });

            modelBuilder.Entity("AbsurdCourt.Domain.Rooms.Room", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
