using AbsurdCourt.Domain.Rooms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AbsurdCourt.Infrastructure.Persistence.Configurations;

public sealed class RoomConfiguration : IEntityTypeConfiguration<Room>
{
    public void Configure(EntityTypeBuilder<Room> builder)
    {
        builder.ToTable("Rooms");
        builder.HasKey(r => r.Id);
        // Every Id in this model is a Guid generated by Domain code (Guid.NewGuid() in
        // aggregate constructors), never by the database — without this, EF's default
        // heuristic for entities reached via navigation (not an explicit Add()) treats a
        // non-default Guid key as "might already exist" and issues an UPDATE instead of an
        // INSERT, which affects 0 rows and surfaces as a bogus DbUpdateConcurrencyException.
        builder.Property(r => r.Id).ValueGeneratedNever();

        builder.Property(r => r.Code)
            .HasConversion(c => c.Value, v => RoomCode.Create(v))
            .HasMaxLength(7)
            .IsRequired();
        builder.HasIndex(r => r.Code).IsUnique();

        builder.Property(r => r.Status).HasConversion<string>().HasMaxLength(16);
        builder.Property(r => r.HostPlayerId);
        builder.Property(r => r.CreatedAtUtc);
        builder.Property(r => r.AwaitingRematchSinceUtc);

        builder.OwnsOne(r => r.Settings, s =>
        {
            s.Property(x => x.CaseCount).HasColumnName("SettingsCaseCount");
            s.Property(x => x.RoundDurationSeconds).HasColumnName("SettingsRoundDurationSeconds");
        });
        builder.Navigation(r => r.Settings).IsRequired();

        builder.Property<HashSet<Guid>>("_rematchReadyPlayerIds")
            .HasColumnName("RematchReadyPlayerIds")
            .HasConversion(GuidCollectionConverters.SetConverter)
            .Metadata.SetValueComparer(GuidCollectionConverters.SetComparer);

        builder.HasMany(r => r.Players)
            .WithOne()
            .HasForeignKey("RoomId")
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(r => r.Players).HasField("_players").UsePropertyAccessMode(PropertyAccessMode.Field);

        builder.Ignore(r => r.DomainEvents);
        builder.Ignore(r => r.ConnectedPlayerIds);
        builder.Ignore(r => r.RematchReadyPlayerIds);
    }
}
